### 🤖 Guía de Asistencia con IA: IA como Copiloto de Programación

En esta notebook, utilizaremos la Inteligencia Artificial como copiloto de aprendizaje. Aquí tienes algunas sugerencias de cómo interactuar con un asistente de IA (como Gemini o ChatGPT):

- **Explicación de código**: Si encuentras una función o línea que no comprendes, pregúntale a la IA: *'Explica qué hace esta función línea por línea en Python: [pega tu código]'*.
- **Corrección de errores**: Si tienes un error al ejecutar, copia el error completo y pregúntale: *'¿Por qué este código genera este error y cómo lo soluciono? [pega tu código y error]'*.
- **Optimización**: Pregunta: *'¿Cómo puedo escribir este código de forma más eficiente y limpia?'*.


# Programa Ingenias+ Data Science

In [ ]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
from google.colab import drive
expvida = pd.read_csv('/content/drive/MyDrive/NOTEBOOKS 2026/life_expectancy_data.csv')

In [ ]:
#Importar numpy
import numpy as np

In [ ]:
array_ceros=np.zeros(12)
print(array_ceros)
len (array_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


12

In [ ]:
#Ejercicio 1: Crear un arreglo de ceros de longitud 12
Ejercicio1=np.zeros(12)
print(Ejercicio1)
len (Ejercicio1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


12

In [ ]:
#prueba: arreglo de unos de longitud 5
prueba=np.ones(5)
print(prueba)

[1. 1. 1. 1. 1.]


In [ ]:
#Ejercicio 2: Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
Ejercicio2=np.zeros(10)
Ejercicio2[4]=10
print(Ejercicio2)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


In [ ]:
#prueba 2: en el arreglo de unos, que la tercer posicion tenga un 7
prueba[3]=7
print(prueba)

[1. 1. 1. 7. 1.]


In [ ]:
#Ejercicio 3: Crear un arreglo que tenga los números del 10 al 49
array_10_49=np.arange(10,50)
print(array_10_49)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#Ejercicio 4: Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
Ejercicio4=np.arange(9).reshape(3,3)
print(Ejercicio4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#Ejercicio 5: Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
Ejercicio5=np.random.rand(100)
print(Ejercicio5)
print("")
media = np.mean(Ejercicio5)
print("Media:", media)
print("")
varianza = np.var(Ejercicio5)
print("Varianza:", varianza)

[0.36211578 0.64093884 0.0173834  0.66435518 0.37902592 0.5889612
 0.03630502 0.6669246  0.77686139 0.67650097 0.15241933 0.33679545
 0.08025523 0.37503959 0.59645844 0.39168051 0.07741195 0.82809584
 0.52417714 0.5562645  0.51491893 0.26746056 0.30865913 0.62943587
 0.46268336 0.29341414 0.5122053  0.49937487 0.0317177  0.14411664
 0.30016767 0.36864648 0.23396331 0.66607428 0.71748202 0.73542022
 0.91737943 0.90008183 0.57820219 0.49480319 0.05147947 0.74007469
 0.43075028 0.16126386 0.55558456 0.14225965 0.60499811 0.08348744
 0.09075713 0.90973408 0.76265274 0.69428601 0.12032487 0.50889178
 0.73416427 0.46493074 0.60238384 0.39837982 0.24856358 0.68859811
 0.84362296 0.14028772 0.24741582 0.07119595 0.78848531 0.07064818
 0.72669896 0.78947    0.94382617 0.20393302 0.43956383 0.41707088
 0.92760275 0.70529144 0.98601158 0.46359095 0.77323303 0.64865472
 0.2617325  0.49568245 0.40483059 0.73407415 0.35237588 0.59642723
 0.90115778 0.85385495 0.66445275 0.83421899 0.70127505 0.10456

In [ ]:
#pruba 5: crear arreglo de 25 numeros aleatorios y calcular media y varianza
Prueba5=np.random.rand(25)
print(Prueba5)
print("")
media25=np.mean(Prueba5)
print("Media:", media25 )
print("")
varianza25=np.var(Prueba5)
print("Varianza:", varianza25)

[9.58960490e-01 9.11908996e-01 6.09399570e-01 5.51464364e-01
 1.70441736e-01 8.51252455e-01 2.90149409e-01 6.31453091e-01
 5.19844350e-01 6.01210824e-01 5.79218334e-01 4.60002103e-01
 5.59265634e-01 7.10199468e-01 4.49462475e-01 2.00781633e-01
 4.14194825e-01 6.80530610e-01 2.40445439e-01 4.49532594e-05
 4.47069790e-01 5.99576504e-01 4.09432003e-01 1.02118627e-01
 2.09719453e-01]

Media: 0.4863258855356895

Varianza: 0.058504975016992714


In [ ]:
#Ejercicio 6: Calcular la media de un arreglo usando np.sum
Ejercicio6 = np.sum(Ejercicio5)/[len(Ejercicio5)]
print(Ejercicio6)

[0.48496585]


In [ ]:
#prueba6: Calcular la media de un arreglo usando np.sum
prueba6=np.sum(Prueba5)/[len(Prueba5)]
print(prueba6)
prueba6a=np.mean(Prueba5)
print(prueba6a)

[0.51794553]
0.517945528660525


In [ ]:
#ejercicio 7: Calcular la varianza de un arreglo usando np.sum y np.mean
Ejercicio7=np.sum((Ejercicio5-np.mean(Ejercicio5))**2)/[len(Ejercicio5)]
print(Ejercicio7)

[0.07382934]


### Visualización de datos del CSV

In [31]:
print("Las primeras 5 filas del DataFrame 'expvida':")
display(expvida.head())

Las primeras 5 filas del DataFrame 'expvida':


NameError: name 'expvida' is not defined

In [ ]:
print("\nInformación general del DataFrame 'expvida' (tipos de datos y valores no nulos):")
expvida.info()

In [ ]:
#Ejercicio8
#Crear un array de números aleatorios usando np.random.randn

Ejercicio8=np.random.rand(15) #en mi caso elegi 15 numeros random
print(Ejercicio8)

[0.02697934 0.12008586 0.70886535 0.1965237  0.61236325 0.37387422
 0.67681061 0.72296588 0.59292141 0.03102055 0.87454306 0.43166587
 0.67468311 0.15194344 0.66626366]
